name: Deploy
on:
  push:
    branches: master
  pull_request:
    branches: master
  
env:
  ASTRO_STUDIO_APP_TOKEN: ${{ secrets.ASTRO_STUDIO_APP_TOKEN }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      
      - name: Add pnpm to Deno Deploy
        run: deno install npm:pnpm

      - name: Install step
        run: "npm i --force"

      - name: Build step
        run: "npm run build --remote"

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "yanquisalexander"
          entrypoint: "server/entry.mjs"
          root: "dist"
